export const blogPostsData = [
  {
    id: "html-basics",
    title: "Getting Started with HTML",
    author: "Alex Dev",
    date: "23 Jun 2025",
    image: "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?auto=format&fit=crop&w=800&q=80",
    alt: "HTML Basics",
    href: "/htmlsection",
    tags: ["HTML", "Beginner", "Web"],
    excerpt: "Learn the building blocks of the web! This post covers HTML essentials for beginners, including tags, structure, and best practices.",
    featured: true,
  },
  {
    id: "css-fundamentals",
    title: "CSS Fundamentals",
    author: "Jamie Styles",
    date: "22 Jun 2025",
    image: "https://images.unsplash.com/photo-1521737852567-6949f3f9f2b5?auto=format&fit=crop&w=400&q=80",
    alt: "CSS Fundamentals",
    href: "/csssection",
    tags: ["CSS", "Styling"],
    excerpt: "Discover how to style your web pages with CSS. Learn about selectors, colors, layouts, and responsive design.",
    featured: false,
  },
  {
    id: "js-essentials",
    title: "JavaScript Essentials",
    author: "Morgan Script",
    date: "21 Jun 2025",
    image: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=400&q=80",
    alt: "JavaScript Essentials",
    href: "/jssection",
    tags: ["JavaScript", "Programming"],
    excerpt: "Start programming the web! This guide introduces JavaScript basics, variables, functions, and DOM manipulation.",
    featured: false,
  },
  // Add more posts as needed...
];